# Generated by Django 5.0.6 on 2024-06-23 09:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('severity', models.TextField(validators=[django.core.validators.RegexValidator(message='Only digits from 1 to 9 are allowed.', regex='^[1-9]*$')])),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Calculated_Illness',
            fields=[
                ('illness', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='calculated_illness', serialize=False, to='health.illness')),
                ('max_severity', models.IntegerField()),
                ('mode_severity', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
