# Generated by Django 5.0.6 on 2024-06-12 20:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=50)),
                ('area', models.CharField(blank=True, default='', max_length=150)),
                ('side', models.CharField(blank=True, default='', max_length=30)),
                ('start_datetime', models.DateTimeField()),
                ('severity', models.TextField(validators=[django.core.validators.RegexValidator(message='Only digits from 1 to 9 are allowed.', regex='^[1-9]*$')])),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calculated_Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_severity', models.IntegerField()),
                ('mode_severity', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('injury', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_injury', to='InjuryApp.injury')),
            ],
        ),
    ]
