# Generated by Django 5.0.6 on 2024-06-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjuryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculated_injury',
            name='id',
        ),
        migrations.AlterField(
            model_name='calculated_injury',
            name='injury',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='calculated_injury', serialize=False, to='InjuryApp.injury'),
        ),
    ]
